// Copies the compiled ArcGift ABI from Foundry output into the web app.
// Run after `forge build`: node scripts/sync-abi.mjs
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const artifact = JSON.parse(readFileSync(join(root, "contracts/out/ArcGift.sol/ArcGift.json"), "utf8"));
const out = `// AUTO-GENERATED by scripts/sync-abi.mjs from contracts/out — do not edit.
export const arcGiftAbi = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
writeFileSync(join(root, "web/src/lib/abi.ts"), out);
console.log(`wrote web/src/lib/abi.ts (${artifact.abi.length} entries)`);
